from fpdf import FPDF


def safe_text(value):
    """
    Converts Gemini Unicode formatting into characters supported
    by FPDF's built-in Helvetica font.
    """
    text = str(value or "")

    replacements = {
        "\u2022": "-",
        "\u25cf": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u00a0": " ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.encode(
        "latin-1",
        errors="replace"
    ).decode("latin-1")


class PregaCarePatientReport(FPDF):

    def header(self):
        self.set_font("helvetica", "B", 20)
        self.set_text_color(79, 70, 229)

        self.cell(
            0,
            15,
            "PregaCare Health Analysis Report",
            ln=True,
            align="C"
        )

        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)

        self.cell(
            0,
            10,
            f"Generated by PregaCare AI - Page {self.page_no()}",
            align="C"
        )

    def chapter_title(self, title):
        self.set_x(self.l_margin)
        self.set_font("helvetica", "B", 16)
        self.set_text_color(31, 41, 55)

        self.cell(
            0,
            10,
            safe_text(title),
            ln=True
        )

        self.ln(2)

        self.set_draw_color(229, 231, 235)
        self.line(
            self.l_margin,
            self.get_y(),
            self.w - self.r_margin,
            self.get_y()
        )

        self.ln(5)

    def chapter_body(self, body):
        self.set_x(self.l_margin)
        self.set_font("helvetica", "", 11)
        self.set_text_color(55, 65, 81)

        self.multi_cell(
            0,
            7,
            safe_text(body)
        )

        self.set_x(self.l_margin)
        self.ln(5)

    def stats_box(
        self,
        label,
        value,
        color=(31, 41, 55)
    ):
        self.set_x(self.l_margin)
        self.set_font("helvetica", "B", 12)
        self.set_text_color(107, 114, 128)

        self.cell(
            50,
            10,
            safe_text(f"{label}:"),
            ln=False
        )

        self.set_font("helvetica", "B", 14)
        self.set_text_color(*color)

        self.cell(
            0,
            10,
            safe_text(value),
            ln=True
        )


def generate_patient_pdf(
    report_data,
    vitals,
    output_path,
    chat_history=None
):
    pdf = PregaCarePatientReport()

    pdf.set_auto_page_break(
        auto=True,
        margin=20
    )

    pdf.add_page()

    # --------------------------------------------------
    # 1. Assessment Summary
    # --------------------------------------------------

    pdf.chapter_title("1. Assessment Summary")

    risk_band = str(
        report_data.get("risk_band", "Unknown")
    )

    risk_color = (16, 185, 129)

    if "mid" in risk_band.lower():
        risk_color = (245, 158, 11)

    elif "high" in risk_band.lower():
        risk_color = (239, 68, 68)

    pdf.stats_box(
        "Overall Risk",
        risk_band.upper(),
        risk_color
    )

    pdf.stats_box(
        "PregaCare Index",
        f"{report_data.get('combined_score', 'N/A')}/100",
        (79, 70, 229)
    )

    pdf.stats_box(
        "Location",
        report_data.get("location", "N/A")
    )

    pdf.ln(5)

    # --------------------------------------------------
    # 2. Clinical Vitals
    # --------------------------------------------------

    pdf.chapter_title("2. Clinical Vitals")

    for key, value in vitals.items():
        pdf.set_x(pdf.l_margin)
        pdf.set_font("helvetica", "", 12)
        pdf.set_text_color(55, 65, 81)

        pdf.cell(
            50,
            8,
            safe_text(f"{key}:"),
            ln=False
        )

        pdf.set_font("helvetica", "B", 12)

        pdf.cell(
            0,
            8,
            safe_text(value),
            ln=True
        )

    pdf.ln(5)

    # --------------------------------------------------
    # 3. AI Insights
    # --------------------------------------------------

    pdf.chapter_title(
        "3. AI Insights & Action Plan"
    )

    pdf.chapter_body(
        report_data.get(
            "suggested_action",
            "No action plan is available."
        )
    )

    # --------------------------------------------------
    # 4. RAG Chat Conversation
    # --------------------------------------------------

    pdf.chapter_title(
        "4. AI Clinical Assistant Conversation"
    )

    if chat_history:
        question_number = 1

        for message in chat_history:
            role = str(
                message.get("role", "")
            ).lower()

            content = str(
                message.get("content", "")
            ).strip()

            if not content:
                continue

            if role == "user":
                pdf.set_x(pdf.l_margin)
                pdf.set_font(
                    "helvetica",
                    "B",
                    12
                )
                pdf.set_text_color(
                    79,
                    70,
                    229
                )

                pdf.multi_cell(
                    0,
                    7,
                    safe_text(
                        f"Question {question_number}:"
                    )
                )

                pdf.set_x(pdf.l_margin)
                pdf.set_font(
                    "helvetica",
                    "",
                    11
                )
                pdf.set_text_color(
                    55,
                    65,
                    81
                )

                pdf.multi_cell(
                    0,
                    7,
                    safe_text(content)
                )

                pdf.set_x(pdf.l_margin)
                pdf.ln(3)

            elif role == "assistant":
                pdf.set_x(pdf.l_margin)
                pdf.set_font(
                    "helvetica",
                    "B",
                    12
                )
                pdf.set_text_color(
                    16,
                    145,
                    100
                )

                pdf.multi_cell(
                    0,
                    7,
                    "PregaCare AI Answer:"
                )

                pdf.set_x(pdf.l_margin)
                pdf.set_font(
                    "helvetica",
                    "",
                    11
                )
                pdf.set_text_color(
                    55,
                    65,
                    81
                )

                pdf.multi_cell(
                    0,
                    7,
                    safe_text(content)
                )

                pdf.set_x(pdf.l_margin)
                pdf.ln(6)

                question_number += 1

    else:
        pdf.chapter_body(
            "No AI Clinical Assistant conversation was recorded."
        )

    # --------------------------------------------------
    # 5. Medical Disclaimer
    # --------------------------------------------------

    pdf.chapter_title(
        "5. Medical Disclaimer"
    )

    pdf.chapter_body(
        "This report was generated using PregaCare's stacking "
        "ensemble model and regional infrastructure analysis "
        "based on NFHS-5 data. AI-generated information is for "
        "general guidance only and is not a medical diagnosis. "
        "Please consult a qualified medical professional."
    )

    # These lines must remain at the end of the function.
    pdf.output(output_path)

    return output_path