name: Sync backend to Hugging Face

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "jatin.2025loq@gmail.com"
          git config --global user.name "jatinXploit"
          git push --force https://jatinXploit:$HF_TOKEN@huggingface.co/spaces/jatinXploit/pregacare-api main